version: "3.8"
services: 
  frontend:
    build: ./
    ports: 
      - '8080:8080'
    volumes: 
      - /app/node_modules
      - ./:/app
    stdin_open: true
    tty: true
    depends_on:
      - api
  api:
    build: ./api
    ports: 
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - db
    env_file:
      - ./env/api.env
  db:
    image: postgres
    restart: always
    env_file: 
      - ./env/db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

volumes:
  pgdata:
